### ISSUE TITLE
io_done() bug

### ISSUE THREAD

**Issue by polluks** [tschak909/platotermamiga#22]
You cannot DoIO() before checking if the device is open.

**Comment by wschaub** [comment]
How do I check if a device is still open or not?  io_done is only called when we want to close a device. I'm perfectly glad to add anything I need to add in the way of sanity checks.

**Comment by polluks** [comment]
@wschaub We have `device_is_opened` but the check too late. You always have to free resources in reverse order.

**Comment by polluks** [comment]
Q: How do you change the device if you have no serial.device?

**Comment by tschak909** [comment]
There is a Device... entry in the Settings menu, which allows you to change
to a different serial.device. If all you have is TCP/IP, you can e.g. use
telser.device to talk to an AmiTCP compatible TCP/IP stack.

-Thom

**Comment by polluks** [comment]
Bad luck: "we couldn't open the default serial.device, exit the program."
I have no chance to use the Settings menu.

**Comment by tschak909** [comment]
seriously, how can you not have serial.device? it's in ROM!

-Thom

**Comment by polluks** [comment]
Take a look at your ADF...

**Comment by polluks** [comment]
That's not the point here, if you try to start PLATOTerm twice, it will fail.
So you should allow the selection without default device.

**Comment by polluks** [comment]
BTW 200 [downloads](http://aminet.net/package/comm/term/PLATOTermAmiga) :-)

**Comment by tschak909** [comment]
Seriously, thank you for posting :) *HUG*

Hopefully we can get the I/O issue out of the way, and I'll call this thing
1.0. (I do want to add print and save image as IFF)

-Thom

**Comment by polluks** [comment]
FYI this is my devlist:
````
address         version rev     opencnt flags   name
------------------------------------------------------------
0x1401B9C4      52      2       101     0x24    timer.device
0x1403FF6C      51      6       18      0x24    input.device
0x14056DC0      51      1       2       0x24    console.device
0x1400E7D8      50      3       0       0x24    ramdrive.device
0x1403FBAC      4       9       2       0x24    usbscsi.device
0x1403FC70      1       13      1       0x24    pciusb.device
0x1410F38C      51      23      9       0x24    ide.device
0x143B6108      50      1       1       0x24    keyboard.device
0x14D6B488      4       4       1       0x24    usbasixeth.device
0x14D7EC28      4       4       1       0x24    serialcp210x.device
0x14D84C38      4       4       1       0x24    usbmodem.device
0x14D7EF90      4       5       1       0x24    serialpl2303.device
0x14D90AB0      4       4       1       0x24    usbparallel.device
0x14D9CEF0      4       4       1       0x24    usbpalm.device
0x14DA36D8      4       4       1       0x24    usbpegasus.device
0x14DC8718      4       4       1       0x24    usbethwrap.device
0x14DD09D8      4       4       1       0x24    usbraw.device
0x14F67730      50      11      2       0x24    sungem_eth.device
0x14F8FE0C      6       7       1       0x24    ahi.device
0x19166330      39      7       0       0x4     printer.device
0x1D695EA8      50      9       1       0x24    clipboard.device
0x22F0FE70      51      10      0       0x24    netinfo.device
0x1CBF4B58      1       40      0       0x4     telser.device
````

**Comment by tschak909** [comment]
how do you not have a serial.device ? (This is an honest question)

**Comment by polluks** [comment]
Indeed, you can see a few Poseidon USB driver.

**Comment by tschak909** [comment]
again...how do you not have a serial.device? :)

-Thom

**Comment by polluks** [comment]
I'm using a PowerBook, however I also have a Pegasos with a serial port. Anyway you cannot rely on specific hardware.
As I told you if you open a device twice (the same unit) it will fail...

**Comment by tschak909** [comment]
Ok. so.. I'll need to add a jump to the requester to enter a device name.
Do you literally have to change this on your system when you install/run
something like NComm or Terminus, etc?

-Thom

**Comment by polluks** [comment]
Right, at the beginning you have to patch the exe, "bandit" are also six letters...

**Comment by catallo** [comment]
It would be nice if it was possible to save the serial device setting. Right now I have to enter it every time I start Platoterm. 

Is it possible to automate the dialing or is it part of the Plato experience?

**Comment by tschak909** [comment]
It should save the preferences when you hit Apply. I'll chalk that up to a
bug I will try to reproduce.

As for automating dialing, I haven't done so, because every WIFI modem has
different syntax for handling dialing (and when I say different, I do mean
different enough that trying to accomodate all of them in code is just
plain awkward.)

-Thom

**Comment by catallo** [comment]
Oh ok, so how about an option where the user can define an own dial string?

**Comment by tschak909** [comment]
yeah, I can add that :) Add an issue and I'll knock it out! :)

**Comment by wschaub** [comment]
How does this version work for you?  
[PLATOTerm.zip](https://github.com/tschak909/platotermamiga/files/2752841/PLATOTerm.zip)

This should have improved handling of open/close of the serial device plus fall back to the requester instead of trying to just quit. I've also fixed a crash where calling done() from inside io_init would cause sound_done to guru because sound_init() wasn't being called yet.  my current testing branch for this is at 
https://github.com/wschaub/platotermamiga/tree/bugfix/issue22 

I haven't done a pull request just yet until I get some more feedback.

**Comment by lastebil** [comment]
That exhibits similar issues to the earlier 1.3 binary - though it seems to return to the SHELL, but not close the window/screen.

(Amiga os 3.1.4, telser.device, xsurf 500)

I am not able to use the 2.x version, as the ADF seems to have an executable with a mangled hunk (i.e. the executable is not able to actually load.)

However, the zip file was much more handy for testing than writing the adf to a floppy (:

**Comment by lastebil** [comment]
On a second attempt at running, the program closed clean.

Snoopdos showed that with this case, it never opened the serial.device, as the config had been saved with the telser.device ; thus it opened that device.

(Still doesn't connect, but it can now close the application.)

**Comment by polluks** [comment]
MorphOS & your non-filling executable:
Text copy is ok
Gfx copy still hits

**Comment by polluks** [comment]
Copy text is ok
Copy gfx hits
You are not using ReadPixel() so the code does work with graphic cards.

**Comment by wschaub** [comment]
in regards to the 2.x ADFs those are just supposed to be (at the moment anyway) the 1.3.x binary shoved into an ADF by itself with an icon. I don't think we have anything distributed that was compiled for 2.x+ target.  as far as not connecting goes have you tried disabling rts/cts? 

I know Thom has managed to use telser successfully but I only have FS-UAE to play with on my end. If any of you are familiar with AmigaOS internals perhaps you can review the code I posted in a previous comment.  I can't really speak to the clipboard stuff as I didn't implement any of that.

**Comment by wschaub** [comment]
Just out of plain curiosity I built the project targeting 2.x+ only in VBCC with +aos68k -lamiga -lauto -lmsoft instead of +kick13 -lamiga -lauto -lm13  It shouldn't as far as I know make a difference since 1.3 should be forward compatible with newer AmigaOS but if you want to try a binary built for kickstart 2.x+ here's one to try out. 
[pterm2x.zip](https://github.com/tschak909/platotermamiga/files/2756783/pterm2x.zip)

**Comment by tschak909** [comment]
@polluks were you able to try the bin that William posted?
-Thom

**Comment by polluks** [comment]
@tschak909 It worked so far.

**Comment by wschaub** [comment]
is -lmieee more compatible with all the possible amigas out there? just want to make the final product as friendly on as many possible amigas as I can here.

**Comment by polluks** [comment]
Well, you have FPU support for free.

**Comment by polluks** [comment]
@wschaub so just drop the math library
